[package]
name = "blvm-commons-fuzz"
version = "0.0.0"
authors = ["AutoFuzz <fuzz@example.com>"]
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
blvm-commons = { path = ".." }
libfuzzer-sys = "0.4"

[dependencies.arbitrary]
version = "1"
features = ["derive"]

